// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Navbar } from "./components/common/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar/>
//         {children}
//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/common/Navbar";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "24/7 Towing & Roadside Assistance | Fast Tow Service USA",
  description:
    "Nationwide 24/7 towing and roadside assistance in the USA for individual drivers and commercial fleets. Jump starts, tire changes, fuel delivery, lockouts, and emergency towing.",
  keywords: [
    "towing service",
    "tow truck near me",
    "roadside assistance",
    "24/7 towing",
    "emergency towing",
    "fleet roadside assistance",
    "commercial towing",
    "USA",
  ],
  // openGraph: {
  //   title: "24/7 Towing & Roadside Assistance Across the USA",
  //   description:
  //     "Reliable towing and roadside assistance for cars, trucks, and fleets anywhere in the USA, available 24/7.",
  //   url: "https://your-domain.com",
  //   siteName: "Your Tow Company Name",
  //   type: "website",
  //   locale: "en_US",
  // },
  // twitter: {
  //   card: "summary_large_image",
  //   title: "24/7 Towing & Roadside Assistance | USA",
  //   description:
  //     "Fast, reliable towing and roadside assistance for drivers and fleets across the USA.",
  // },
  // metadataBase: new URL("https://your-domain.com"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-brand-mutedBg text-slate-900">
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
