// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Navbar } from "./components/common/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar/>
//         {children}
//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/common/Navbar";
import { Footer } from "./components/common/Footer";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "24/7 Towing & Roadside Assistance | Fast Tow Service USA",
  description:
    "Nationwide 24/7 towing and roadside assistance in the USA for individual drivers and commercial fleets. Jump starts, tire changes, fuel delivery, lockouts, and emergency towing.",
  keywords: [
    "towing service",
    "tow truck near me",
    "roadside assistance",
    "24/7 towing",
    "emergency towing",
    "fleet roadside assistance",
    "commercial towing",
    "USA",
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-brand-mutedBg text-slate-900 selection:bg-brand-primary selection:text-white antialiased">
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
